name: "Auto Changelog Between Tags"
description: "Automatic Changelog generator between the latest two tags"
author: "Ryan Cha"
branding:
  icon: "clock"
  color: "blue"
inputs:
  token:
    description: "Github token"
    required: true
  exclude:
    description: "Exclude selected commit types (comma separated)"
    required: false
    default: ""
outputs:
  changelog:
    description: "The generated changelogs markdown strings"
runs:
  using: "node12"
  main: "action/index.js"
