name: Create Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      RELEASE: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - id: changelog
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
          commitish: "master"
